---
# tasks file for ansible-nagiosxi-server

- name: Fetch Nagios latest stable release
  get_url: url=https://assets.nagios.com/downloads/nagiosxi/5/xi-5.8.2.tar.gz dest=/root

- name: Extact Nagios latest release
  unarchive: 
    src: /root/xi-5.8.2.tar.gz 
    dest: /root 
    copy: no
    creates: /root/nagiosxi

- name: Install packages
  yum:
    name: ['epel-release' ,'initscripts', 'openssh-server', 'ncurses', 'crontabs', 'cronie', 'which']
    state: present

- name: Install PHP packages
  yum:
    name: ['php', 'php-fpm', 'php-common']
    state: present

- name: Upgrade all packages
  yum:
    name: '*'
    state: latest

- name: PHP-FPM Config - update owner
  replace:
    path: "{{ nagios_php_config_path }}"
    regexp: ';listen.owner = nobody'
    replace: 'listen.owner = {{ nagios_http_user }}'

- name: PHP-FPM Config - update group
  replace:
    path: "{{ nagios_php_config_path }}"
    regexp: ';listen.group = nobody'
    replace: 'listen.group = {{ nagios_http_user }}'
    
# Nagios XI full Installation

- name: Nagios Full Install
  command: ./fullinstall -n
  args:
    chdir: /root/nagiosxi
    creates: /etc/pki/rpm-gpg/RPM-GPG-KEY-NAGIOS

# Custom Configuration
- name: Copy Nagios custom config files 
  copy: 
    src: files/{{ item }} 
    dest: "{{ nagios_conf_dir }}"
    mode: 0644
  with_items: '{{ nagios_custom_config_files }}'

- name: Reconfigure Nagios to apply custom config
  command: sh {{ nagiosxi_script_path }}/reconfigure_nagios.sh

# Restart Nagios Service
- name: Restart Nagios service
  command: systemctl restart nagios.service
  become: true